fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      # for future parser tests with puppet < 4
      ref: "4.25.1"
    yum_autoupdate: "https://github.com/antoineco/aco-yum_autoupdate"
  symlinks:
    autoupdate: "#{source_dir}"
